config/routes.rb
resources :wiki_tags, only: [:index, :show]

app/controllers/wiki_tags_controller.rb
class WikiTagsController < ApplicationController
  before_action :find_project

  def index
    @tags = WikiContent.for_project(@project)
  end

  def show
    @pages = WikiContent.joins(page: :wiki).where(
      wikis: {
        project_id: @project.id
      }
    ).where(
      [
        '? = ANY (tags) OR text ILIKE ?',
        params[:id],
        "%category:\"#{params[:id]}\"%"
      ]
    ).order('wiki_pages.title')
  end

  private

  def find_project
    @project = Project.find(params[:project_id])
  end
end

app/views/wiki/_content.html.erb
<div class="wiki wiki-page">
  <% c = textilizable(content, :text, :attachments => content.page.attachments,
        :edit_section_links => (@sections_editable && {:controller => 'wiki', :action => 'edit', :project_id => @page.project, :id => @page.title})) %>
  <%= insert_category_links(c, @project).html_safe %>
  <div class="wiki-tags">
    <% content.tags&.select{ |x| x.present? }&.each do |tag| %>
      <%= link_to tag, wiki_tag_path(tag, project_id: @project), class: 'wiki-tag' %>
    <% end %>
  </div>
</div>

<% content_for :header_tags do %>
  <%= stylesheet_link_tag 'jquery.mentions', plugin: :redmine_wiki_tags %>
<% end %>

app/views/wiki/_sidebar.html.erb
<% if @wiki && @wiki.sidebar -%>
  <div class="wiki">
    <%= textilizable @wiki.sidebar.content, :text %>
  </div>
<% end -%>

<h3><%= l(:label_wiki) %></h3>
<ul>
  <li><%= link_to(l(:field_start_page), {:controller => :wiki, :action => 'show', :project_id => @project}) %></li>
  <li><%= link_to(l(:label_index_by_title), {:controller => :wiki, :action => 'index', :project_id => @project}) %></li>
  <li><%= link_to(l(:label_index_by_date),
                  {:controller => 'wiki', :project_id => @project,
                   :action => 'date_index'}) %></li>
  <li><%= link_to(l(:label_index_by_tags),
                  {:controller => 'wiki_tags', :project_id => @project,
                   :action => 'index'}) %></li>
</ul>

app/views/wiki/edit.html.erb
<%= wiki_page_breadcrumb(@page) %>

<h2><%= @page.pretty_title %></h2>

<%= form_for @content, :as => :content,
             :url => {:action => 'update', :id => @page.title},
             :html => {:method => :put, :multipart => true, :id => 'wiki_form'} do |f| %>
  <%= f.hidden_field :version %>
  <% if @section %>
    <%= hidden_field_tag 'section', @section %>
    <%= hidden_field_tag 'section_hash', @section_hash %>
  <% end %>
  <%= error_messages_for 'content' %>

  <div class="box tabular">
    <%= text_area_tag 'content[text]', @text, :cols => 100, :rows => 25, :accesskey => accesskey(:edit),
                      :class => 'wiki-edit',
                      :data => {
                        :auto_complete => true
                      }
    %>

    <% if @page.safe_attribute_names.include?('parent_id') && @wiki.pages.any? %>
      <%= fields_for @page do |fp| %>
        <p>
          <label><%= l(:field_parent_title) %></label>
          <%= fp.select :parent_id,
                        content_tag('option', '', :value => '') +
                          wiki_page_options_for_select(
                            @wiki.pages.includes(:parent).to_a -
                              @page.self_and_descendants, @page.parent) %>
        </p>
      <% end %>
    <% end %>

    <p><label><%= l(:field_comments) %></label><%= f.text_field :comments, :size => 120, :maxlength => 1024 %></p>
    <fieldset>
      <legend><%=l(:label_attachment_plural)%></legend>
      <% if @page.attachments.any? && @page.safe_attribute?('deleted_attachment_ids') %>
        <div class="contextual"><%= link_to l(:label_edit_attachments), '#', :onclick => "$('#existing-attachments').toggle(); return false;" %></div>
        <div id="existing-attachments" style="<%= @page.deleted_attachment_ids.blank? ? 'display:none;' : '' %>">
          <% @page.attachments.each do |attachment| %>
            <span class="existing-attachment">
              <%= text_field_tag '', attachment.filename, :class => "icon icon-attachment filename", :disabled => true %>
              <label class='inline'>
                <%= check_box_tag 'wiki_page[deleted_attachment_ids][]',
                                  attachment.id,
                                  @page.deleted_attachment_ids.include?(attachment.id),
                                  :id => nil, :class => "deleted_attachment" %> <%= l(:button_delete) %>
              </label>
            </span>
          <% end %>
          <hr />
        </div>
      <% end %>
      <div id="new-attachments" style="display:inline-block;">
        <%= render :partial => 'attachments/form' %>
      </div>
    </fieldset>
  </div>
  <p style='min-height: 3rem'>
    <label><%= l(:field_tags) %></label>
    <%= f.select :tags, WikiContent.for_project(@project), {}, multiple: true, style: 'width: 95%' %>
  </p>
  <p>
    <%= submit_tag l(:button_save) %>
    <%= link_to l(:button_cancel), wiki_page_edit_cancel_path(@page) %>
  </p>
  <%= wikitoolbar_for 'content_text', preview_project_wiki_page_path(:project_id => @project, :id => @page.title) %>

  <% if User.current.allowed_to?(:add_wiki_page_watchers, @project)%>
    <%= update_data_sources_for_auto_complete({users: watchers_autocomplete_for_mention_path(project_id: @project, q: '', object_type: 'wiki_page', object_id: @page.id)}) %>
  <% end %>
<% end %>

<% content_for :header_tags do %>
  <%= robot_exclusion_tag %>
  <%= javascript_include_tag 'select2', plugin: :redmine_wiki_tags %>
  <%= stylesheet_link_tag 'select2', plugin: :redmine_wiki_tags %>

  <script type='text/javascript'>
      $(function() {
          $("#content_tags").select2({ tags: true })
      })
  </script>
<% end %>

<% html_title @page.pretty_title %>

app/views/wiki_tags/index.html.erb
<div class="contextual">
<% if User.current.allowed_to?(:edit_wiki_pages, @project) %>
<%= link_to l(:label_wiki_page_new), new_project_wiki_page_path(@project), :remote => true, :class => 'icon icon-add' %>
<% end %>
</div>

<h2><%= l(:label_index_by_tags) %></h2>

<% @tags.each do |tag| %>
  <p>
    <%= link_to tag, wiki_tag_path(tag, project_id: @project) %>
  </p>
<% end %>

<% content_for :sidebar do %>
  <%= render :partial => 'wiki/sidebar' %>
<% end %>

<% content_for :header_tags do %>
  <%= auto_discovery_link_tag(:atom, :controller => 'activities', :action => 'index', :id => @project, :show_wiki_edits => 1, :format => 'atom', :key => User.current.rss_key) %>
<% end %>

app/views/wiki_tags/show.html.erb
<div class="contextual">
<% if User.current.allowed_to?(:edit_wiki_pages, @project) %>
<%= link_to l(:label_wiki_page_new), new_project_wiki_page_path(@project), :remote => true, :class => 'icon icon-add' %>
<% end %>
</div>

<h2><%= l(:label_tagged_with, tag: params[:id]) %></h2>

<ul class='pages-hierarchy'>
  <% @pages.each do |page| %>
    <%= link_to page.page.title, project_wiki_page_path(@project, page.page.title) %>
    <br />
  <% end %>
</ul>
<% content_for :sidebar do %>
  <%= render :partial => 'wiki/sidebar' %>
<% end %>

<% content_for :header_tags do %>
  <%= auto_discovery_link_tag(:atom, :controller => 'activities', :action => 'index', :id => @project, :show_wiki_edits => 1, :format => 'atom', :key => User.current.rss_key) %>
<% end %>